

# Generated by Django 3.0.3 on 2020-03-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=64)),
                ('receiver', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=4)),
                ('month', models.IntegerField(max_length=2)),
                ('field', models.CharField(max_length=16)),
                ('invention', models.CharField(max_length=10240)),
            ],
            options={
                'db_table': 'circular',
            },
        ),
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'claims',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('fname', models.CharField(max_length=32)),
                ('mname', models.CharField(max_length=32)),
                ('lname', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=6)),
                ('degree', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=64, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
