

# Generated by Django 3.0.3 on 2020-03-30 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CDD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claims',
            name='accident_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claims',
            name='accident_front',
            field=models.CharField(default='help', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claims',
            name='accident_left',
            field=models.CharField(default='help', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claims',
            name='accident_rear',
            field=models.CharField(default='help', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claims',
            name='accident_right',
            field=models.CharField(default='help', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claims',
            name='cost_estimation',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='email',
            field=models.EmailField(default='john@deo.bom', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claims',
            name='message',
            field=models.CharField(default='message', max_length=10240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claims',
            name='processed',
            field=models.CharField(default='Pending', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='total_claims',
            field=models.IntegerField(default=0),
        ),
    ]
