

# Generated by Django 3.0.3 on 2020-03-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CDD', '0002_auto_20200330_2314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Claims',
        ),
    ]
