

# Generated by Django 3.0.3 on 2020-03-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDD', '0003_delete_claims'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=64)),
                ('accident_date', models.DateField()),
                ('accident_front', models.CharField(max_length=128)),
                ('accident_rear', models.CharField(max_length=128)),
                ('accident_left', models.CharField(max_length=128)),
                ('accident_right', models.CharField(max_length=128)),
                ('message', models.CharField(max_length=10240)),
                ('processed', models.CharField(default='Pending', max_length=8)),
                ('cost_estimation', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'claims',
            },
        ),
    ]
