
# Generated by Django 3.0.3 on 2020-03-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDD', '0004_claims'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartCost',
            fields=[
                ('make', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('hood', models.IntegerField()),
                ('bumper', models.IntegerField()),
                ('windshield', models.IntegerField()),
                ('door', models.IntegerField()),
                ('light', models.IntegerField()),
                ('roof', models.IntegerField()),
                ('sideglass', models.IntegerField()),
                ('window', models.IntegerField()),
            ],
            options={
                'db_table': 'partcost',
            },
        ),
    ]
