
# Generated by Django 3.0.3 on 2020-03-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDD', '0005_partcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circular',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='circular',
            name='year',
            field=models.IntegerField(),
        ),
    ]
